---
title: "2024 Spring · CSE Department Seminars"
---

Welcome to the CSE Department Seminars for the Spring term of 2024! We are excited to announce an amazing lineup of speakers this semester. Unless mentioned otherwise:

- all talks are hybrid, and you can join us either at `1/201`^[The speakers are typically present in person.] if you are on campus, or over [Zoom](
https://iitgn-ac-in.zoom.us/j/5086558236?pwd=bXl6NXFpQURVWnJZaDJucUpqN3hUZz09&omn=94677480599)^[The passcode is `t____g`. This is the first word in the popular phrases `****** test` and `****** award`. ChatGPT knows the answer too.];
- are 50 minutes long, followed by 10 minutes of Q&A;
- and start on Fridays at 3:30PM (except when there are multiple talks).

Please send an email to `neeldhara.m@iitgn.ac.in` if you see an unclaimed Friday and would like to give a talk in this series.

:::{.callout-caution icon="false" collapse="true"} 
# Sign up for reminders

<iframe style="border:none;width:100%;" height="420px" src="https://opnform.com/forms/my-form-1bmcse"></iframe>
:::

:::{.callout-important appearance="minimal"}

{{< bi card-text color="indianred" >}} We have some signed collectibles that will be handed out to the in-person attendees and it'll be a different one every week --- can you collect them all? :)
:::

<!-- begin panel -->
::: {.panel-tabset}

## Up Next

TBA.

## Upcoming Talks


:::{.callout-warning icon="false" collapse="true"}
# `15-03-2024` · TBA
:::

---

:::{.callout-warning icon="false" collapse="true"}
# `22-03-2024` · TBA
:::

---

:::{.callout-note icon="false" collapse="true"}
# `05-04-2024` · Coming Soon, Stay Tuned!

:::

:::{.callout-tip icon="false" collapse="true"}
# About The Speaker  · Supreet Saini

Supreet Saini obtained his BTech in Chemical Engineering from IIT Delhi in 2005 and PhD in Chemical & Biomolecular Engineering from University of Illinois, Urbana-Champaign in 2010. Supreet is a Professor & a DBT/Wellcome Trust (India Alliance) Fellow in the Department of Chemical Engineering at IIT Bombay. Prior to joining IIT Bombay, he was an Assistant Professor of Chemical Engineering at IIT Gandhinagar (2010-2012), where he also headed the Faculty Recruitment Committee among other responsibilities. He is the recipient of the Young Engineer Award 2017 (Indian National Academy of Engineering) and the Innovative Young Biotechnologist Award 2011 (Department of Biotechnology). His research interests are in the area of evolutionary microbiology.
:::

---

:::{.callout-warning icon="false" collapse="true"}
# `12-04-2024`  · TBA
:::

---

:::{.callout-warning icon="false" collapse="true"}
# `19-04-2024`  · TBA
:::

## Past Talks

:::{.callout-note icon="false" collapse="true"}
# `02-03-2024` · `4PM to 5PM` · How languages influence thinking

In this talk, which I will try to run like a pair programming session, we will analyze how programming language features determine or influence the process of building solutions. This is one side of the programming language analogue of linguistic determinism, linguistic relativity, and language universalism from the theory of (natural) languages.

:::

:::{.callout-tip icon="false" collapse="true"}
# About the Speaker · Balagopal Komarath

Among other things, Balagopal Komarath is interested in the process by which people learn programming and how learners at different stages approach problem solving through programming.

:::

---

:::{.callout-note icon="false" collapse="true"}
# `23-02-2024` · `3:30PM to 4:30PM` · Making recursion simple, by making recursion simple

The Y (and Z) combinators are theoretical constructs that allow us to express recursion from first principles. In this talk, which requires no foundation in mathematics or theory, I'll write code and evolve these combinators in F#, and show how powerful they are.

You should get a deeper appreciation for the power of functional programming and some of the benefits of applying theoretical foundations...

:::

:::{.callout-tip icon="false" collapse="true"}
# About the Speaker · John Azariah

John has over 30 years of experience writing all kinds of software, and was one of the original designers of the Microsoft Q# language for Quantum Computing.

He is a frequent speaker at conferences on various topics of expertise including on functional programming, cloud computing, quantum computing and software engineering.

He currently works on the AKS team at Microsoft and is based in Brisbane, Australia with his wife and daughter.

:::

---

:::{.callout-note icon="false" collapse="true"}
# `02-02-2024` · `2PM to 3PM` · Computing music: Crossing the left-right brain divide

The history of computer music is nearly as old as computing itself. It has therefore borrowed and tracked various paradigms of programming and systems engineering in the course of its development and also introduced niche paradigms of its own. The domain offers a unique way to engage with computing for those with some ties to music, and vice versa. Teaching a class with students having diverse capabilities and interests therefore poses interesting challenges of individual development and group work. For context, I'll present some of the history of the domain and the modes of thinking that the field has employed, with a sample of various "languages", systems and methods in use. I'll then bring up some challenges of teaching it to a class, primarily around how to get students comfortable crossing the left-right brain divide.

:::

:::{.callout-tip icon="false" collapse="true"}
# About the Speaker · Srikumar Subramanian

Srikumar is currently a visiting professor of practice in the dept of Computer Science at Krea University, and also an "associate director", part of Accenture Technology Labs. His primary background is in audio and visual signal processing and he has worked in the "computing meets the arts" area for over a decade, with initial work on interactive music composition, followed by automating the construction of music videos in various programmed styles at muvee Technologies in Singapore, and modelling gamakas of Carnatic music for his PhD at NUS. He often has his fingers in many pies at the same time and enjoys that. His interest in teaching CS arose from his interest in programming languages that deepened while working on "muSE" -- a Scheme dialect he made for automatic video construction. Needless to say, he draws heavy inspiration from the work of the Racket team, from way back when it was MzScheme.

:::

---

:::{.callout-note icon="false" collapse="true"}
# `02-02-2024` · `3PM to 4PM` · Functional Programming with Haskell -- A Teaser

We provide a quick tour of the functional programming language Haskell, touching on the highlights like pattern matching, polymorphism, higher-order functions etc. We will focus on laziness, an essential feature that sets it apart from other functional languages, and two examples that illustrate how laziness helps in writing simple programs for complex tasks.

:::

:::{.callout-tip icon="false" collapse="true"}
# About the Speaker · S P Suresh

S P Suresh is on the faculty of Theoretical Computer Science at the Chennai Mathematical Institute. His research interests include logic in computer science, concurrency and distributed computing, and formal methods for security. He did his PhD at the Institute of Mathematical Sciences with Jam.

His other interests include classical Indian logic and epistemology, Carnatic music, chess, and P G Wodehouse. And his mission in life is to prove beautiful theorems and present them in beautifully typeset papers!
:::

---

:::{.callout-note icon="false" collapse="true"}
# `02-02-2024` · `4:30PM to 5:30PM` · Programming Before You Program

Programming education, seemingly obviously, focuses on the writing of programs. But when novices struggle with programming, a lot of their difficulty is not with the program per se. What else is there? What do we know about it? And how can we make their experience better? This talk summarizes computing education research that asks and answers these questions.

:::

:::{.callout-tip icon="false" collapse="true"}
# About the Speaker · Shriram Krishnamurthi

Shriram is the Vice President for Programming Languages at Brown University in Providence, RI, USA. He’s not, really, but that’s what it says on his business card. At heart, he's a person of ill-repute: a Schemer, Racketeer, and Pyreteer. He believes tropical fruit are superior to all other kinds. He is terrified of success, because he may be forced to buy a suit. He is known to interrogate his audiences to ensure they’re paying attention. So, be alert. You can read email later.

:::

---

The talk below is also a part of the *Sabarmati Young Researchers Seminar Series (SYRSS)*.

:::{.callout-note icon="false" collapse="true"}
# `19-01-2024` · Shield: Secure Allegation Escrow System with Stronger Guarantees

The rising issues of harassment, exploitation, corruption, and other forms of abuse have led victims to seek comfort by acting in unison against common perpetrators (e.g., #MeToo movement). One way to curb these issues is to install allegation escrow systems that allow victims to report such incidents. The escrows are responsible for identifying victims of a common perpetrator and taking the necessary action to bring justice to them. However, users hesitate to participate in these systems due to the fear of such sensitive reports being leaked to perpetrators, who may further misuse them. Thus, to increase trust in the system, cryptographic solutions are being designed to realize secure allegation escrow (SAE) systems. 

In the work of Arun et al. (NDSS'20), which presents the state-of-the-art solution, we identify attacks that can leak sensitive information and compromise victim privacy. We also report issues present in prior works that were left unidentified. To arrest all these breaches, we put forth an SAE system that prevents the identified attacks and retains the salient features from all prior works. The cryptographic technique of secure multi-party computation (MPC) serves as the primary underlying tool in designing our system. At the heart of our system lies a new duplicity check protocol and an improved matching protocol. We also provide additional features such as allegation modification and deletion, which were absent in the state of the art. To demonstrate feasibility, we benchmark the proposed system with state-of-the-art MPC protocols and report the cost of processing an allegation. Different settings that affect system performance are analyzed, and the reported values showcase the practicality of our solution.

:::

:::{.callout-tip icon="false" collapse="true"}
# About the Speaker · Varsha Bhat

Dr. Varsha Bhat was previously a post-doctoral researcher at the Cryptography and Information Security Lab of IISc under the Prof. Arpita Patra. She completed her PhD from Indian Institute of Technology Ropar, under the guidance of Dr. Sudarshan Iyengar. Prior to this, she completed her B.E. in Computer Science and Engineering from Dayananda Sagar College of Engineering (under VTU). So far, the focus of her research has been on designing secure solutions for various real-world applications, including those with financial and social relevance, using the techniques of secure multiparty computation (MPC).

:::

---


:::{.callout-note icon="false" collapse="true"}
# `05-01-2024` · Understanding Problems Before Programming

Novice programmers often begin coding with a poor understanding of the task at hand and end up solving the wrong problem. To combat this, students are often asked to explain the problem in their own words. What words can students use meaningfully, how can we provide automated feedback, and how can we make this feedback maximally useful? This talk presents concrete solutions to all these problems.

:::

:::{.callout-tip icon="false" collapse="true"}
# About the Speaker · Siddhartha Prasad

Siddhartha Prasad is a PhD student at Brown University, working on formal methods, education, and programming languages.  His current research aims to help programmers better understand the problems they are solving. Previously, he was a software engineer at Microsoft, working on Azure Cognitive Services and the XAML UI framework.

:::

---

:::{.callout-note icon="false" collapse="true"}
# `29-12-2023` · How many Clusters ? - An Algorithmic Answer

Many algorithms for clustering high dimensional data assume that k, the number of clusters, is given. However, there has been little work on provably inferring k from the data. In this talk, I shall describe polynomial time algorithms for fi€nding k from the data assuming it satisfies certain natural deterministic conditions. Informally, we assume that there is a Ground Truth (GT) clustering of the data with the following properties: (i) Each cluster has a certain minimum size, (ii) the inter-mean separation of any two distinct clusters in the GT is large enough (although still weaker than what is typically assumed in the literature), and (iii) we define a novel “no large sub-cluster”(NLSC) property that characterizes the notion of a cluster
by stipulating that there be no subsets of low “directional variance”. NLSC is indeed satisfied by a large class of distributions including log-concave densities.  This is joint work with Chiranjib Bhattacharyya and Ravindran Kannan.

:::

:::{.callout-tip icon="false" collapse="true"}
# About the Speaker · Amit Kumar

Amit Kumar is Professor in the Department of Computer Science and Engineering at the Indian Institute of Technology Delhi. He received his B.Tech. degree from Indian Institute of Technology Kanpur in 1997, and Ph.D. from Cornell University in 2002. He worked as Member of Technical Staff at Bell Labs, Murray Hill, New Jersey, U.S. during 2002–2003. He joined IIT Delhi as faculty member in 2003. He works in the area of combinatorial optimization, approximation algorithms and online algorithms. He is working extensively on problems arising in scheduling theory, clustering, and graph theoretic algorithmic problems.
:::

---

:::{.callout-note icon="false" collapse="true"}
# `22-12-2023` · A Gale-Shapley View of Unique Stable Marriages

Stable marriage of a two-sided market with unit demand is a classic problem that arises in many real-world scenarios. In addition, a unique stable marriage in this market simplifies a host of downstream desiderata. In this paper, we explore a new set of sufficient conditions for unique stable matching (USM) under this setup. Unlike other approaches that also address this question using the structure of preference profiles, we use an algorithmic viewpoint and investigate if this question can be answered using the lens of the deferred acceptance (DA) algorithm (Gale and Shapley, 1962). Our results yield a set of sufficient conditions for USM (viz., MaxProp and MaxRou) and show that these are disjoint from the previously known sufficiency conditions like sequential preference and no crossing. We also provide a characterization of MaxProp that makes it efficiently verifiable, and shows the gap between MaxProp and the entire USM class. These results give a more detailed view of the sub-structures of the USM class.

This is a joint work with Kartik Gokhale, Amit Kumar Mallik, and Ankit Kumar Misra. 

[Slides](https://docs.google.com/presentation/d/10DClCFmC1PRbzBDeHX4dUT8hNgIlodvfHpRKEDmVr4c/edit?usp=sharing) · [ArXiV](https://arxiv.org/abs/2310.18736)
:::

:::{.callout-tip icon="false" collapse="true"}
# About the Speaker · Swaprava Nath

Swaprava is an Assistant Professor at the Department of Computer Science and Engineering, IIT Bombay. Before this, he was a faculty member at the Dept. of CSE, IIT Kanpur. Even earlier, he held postdoctoral positions at Carnegie Mellon University and Indian Statistical Institute, New Delhi, and finished his PhD from the Dept. of CSA, IISc Bangalore. His research interest lies at the intersection of economics and computation, which has several applications in social and industrial paradigms (for details, please see his [CompEcon group page](https://www.cse.iitb.ac.in/~swaprava/group.html) and his [research page](https://www.cse.iitb.ac.in/~swaprava/research.html)). His work has been published in top AI and multiagent systems conferences, e.g., AAAI, IJCAI, AAMAS, WINE, and also in economics and management venues, e.g., Games and Econ Behavior, Economics Letters, Management Science. Apart from academic positions, Swaprava also has experience in the industry. He has worked at Xerox Research Centre Europe and Cisco Systems India. He has been recipients of Fulbright-Nehru postdoctoral grant, Tata Consultancy Services PhD Fellowship, and the Honorable Mention Award of Yahoo! Key Scientific Challenges Program.
:::


:::
<!-- end panel -->

